Add status-culumn to articles
takumifujii98/hello_world_rails pull request #7
Opened 2019-07-12 13:47 UTC by takumifujii98

##概要
- statusカラムの追加
- articles_controllerの変更

2019-07-12 14:17 UTC, mc-chinju reviewed
Comments !

2019-07-12 14:17 UTC, mc-chinju commented on app/controllers/articles_controller.rb
> +    Article.expressed.find(params[:id])
ここは `expressed` ではなくて、 `published` ですかね？
こういうちょっとしたミスを防ぐという意味でも、テストコードを一緒に書くといいんですよね。（今回の課題ではテストを書くのは出していないのでもちろんなくていいのですが、テストのメリットを感じていただけるかなと。）

2019-07-12 14:17 UTC, mc-chinju commented on app/controllers/articles_controller.rb
> +    Article.expressed.find(params[:id])
あと、 if ~ else ~ は、インデントをいれるようにしたほうが読みやすいです 👍

2019-07-12 14:17 UTC, mc-chinju commented on app/models/article.rb
> +  enum status: {draft: 0, published: 1}
ここは単に好みの話なのですが、僕は enum は integer で管理するより string で管理したほうがよい派です。
というのも、例えばこの status に状態を追加したくなったとします。

 - `published` (公開)
 - `reserved` (公開予約)
 - `draft` (下書き)
 - `prohibited` (強制非公開)

この status をここに追加すべきかどうか、というツッコミはさておき、とにかく追加したくなったとします。
これを単にナンバリングすると 0, 1, 2 ,3 と順につけることになるのですが、このようにナンバリングすると、後から追加されたものが後ろの番号になっていきますよね。

このようにナンバリングすると、後ろの番号のもののほうが、状態的に後に発生するのかな？といったようにも見えてしまうのですが、string で管理していると、どの状態も順序に意味がなく、追加実装でも順序を自在に変えても不自然にならないというメリットがあります。

ちょっと小難しい話ですが、一応頭の片隅にでも入れておいてください 👍
繰り返しになりますが、好みの話なのでこのままでももちろん OK です。

2019-07-12 14:17 UTC, mc-chinju commented on app/controllers/articles_controller.rb
> +    #Article.published = Article.where(status: :published)
学習用のリポジトリとしては Good ！
参考になる URL をコメントするといったこともアリです！

2019-07-12 14:35 UTC, takumifujii98 commented on app/controllers/articles_controller.rb
> +    Article.expressed.find(params[:id])
publishedですね...汗
目視とは段違いに楽かつ確実にミスが見つけられますものね。
テストコードの重要度を再確認しました！
インデント、確かに今のままだと読みにくい...直します！

2019-07-12 14:40 UTC, takumifujii98 commented on app/models/article.rb
> +  enum status: {draft: 0, published: 1}
おー、なるほど！
stringで管理すると自分以外の人が読むときにもわかりやすそうですし、何より自分で読むときもわかりやすそうですね！
練習のしたいのでstringで書き直してみます！

2019-07-13 09:41 UTC, mc-chinju requested changes
show でインスタンス変数に値を代入するのは必須。

2019-07-13 09:41 UTC, mc-chinju commented on app/controllers/articles_controller.rb
> +    end
そういえば、 `@article` に代入していないので view に値が渡らないですね。

```rb
@article = 
  if current_user
    current_user.articles.find(params[:id])
  else
    Article.published.find(params[:id])
  end
```

のようにしないとですね。

2019-07-13 09:41 UTC, mc-chinju commented on db/schema.rb
> +    t.integer "status", default: 0
schema.rb が修正されていないですね。

`rails db:migrate` したあとに、再度 `rails db:migrate` しても、すでに migration が実行されているので更新されません。
なので、 `rails db:rollback` したあとに `rails db:migrate` するか、 `rails db:migrate:reset` する必要があります。

このあたりは、以下の記事を読めばわかるかと！
https://freelance.cat-algorithm.com/migration-commands/

2019-07-14 19:04 UTC, mc-chinju approved these changes
LGTM！

2019-07-15 15:48 UTC, merged